name: Full-year calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 1 *'  # roda todo 1ยบ de janeiro ร meia-noite (UTC)

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate full-year calendar metric
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Commit and push metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.isocalendar.fullyear.svg
          git commit -m "Update full-year calendar metric"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
